#!/bin/sh

set -e

if [ "$1" = remove -o "$1" = "abort-install" -o "$1" = disappear ]; then
    tmpdir=$(mktemp --tmpdir -d session-node.XXXXXXXXXX)

    ucfr --purge session-node /etc/oxen/oxen.conf

    if [ -f "/etc/oxen/oxen.conf" ]; then
        cp /etc/oxen/oxen.conf $tmpdir/oxen.conf
    elif [ -f "/etc/oxen/oxen.conf.no-service-node" ]; then
        cp /etc/oxen/oxen.conf.no-service-node $tmpdir/oxen.conf
    else
        echo "Internal error: cannot find an existing oxen.conf to update!"
        exit 0
    fi

    # Try to merge any changes from the service node config back into the non-service node
    # config when removing the service-node package, but with `service-node=1` commented out.
    sed -i 's/^service-node=/#&/' $tmpdir/oxen.conf
    rm -f /etc/oxen/oxen.conf
    dpkg-divert --package session-node --remove --rename --divert /etc/oxen/oxen.conf.no-service-node /etc/oxen/oxen.conf
    ucf --purge /etc/oxen/oxen.conf
    ucf --debconf-ok $tmpdir/oxen.conf /etc/oxen/oxen.conf
    ucf --purge /etc/oxen/oxen.conf

    rm -rf $tmpdir
fi

#DEBHELPER#
